sudo: required

language: go

matrix:
  include:
    - go: 1.5
      os: linux
      env: REPORT_COVERAGE=true GO15VENDOREXPERIMENT=1
      sudo: required
      dist: trusty
    - go: 1.5
      os: osx
      env: REPORT_COVERAGE=false GO15VENDOREXPERIMENT=1
    - go: tip
      os: linux
      env: REPORT_COVERAGE=false
      sudo: required
      dist: trusty
    - go: tip
      os: osx
      env: REPORT_COVERAGE=false
  fast_finish: true
  allow_failures:
  - go: tip

addons:
  apt:
    sources:
      # - deadsnakes
      - sourceline: 'ppa:fkrull/deadsnakes'
      #- sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
    packages:
      - libonig-dev
      - python3.5
      - python3.5-dev
      - qtdeclarative5-private-dev
      - qtbase5-private-dev
      - libqt5opengl5
      - libqt5opengl5-dev

install:
  - make travis

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
      export DISPLAY=':99.0'
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x32
      echo "Done! Yay! $?"
    fi

script:
  - make travis_test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e692a5224c8490f19bd
    on_success: change
    on_failure: always
    on_start: false
